pipeline{
    agent any
    tools{
        jdk 'jdk17'
        terraform 'terraform'
    }
    stages{
        stage('clean Workspace'){
            steps{
                cleanWs()
            }
        }
        stage('checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/akaspatranobis/Tetris-Game-Project.git'
            }
        }
        stage('Terraform version'){
             steps{
                 dir('Jenkins-CICD') {
                    sh 'terraform --version'
                    }
                }
        }
        stage("Sonarqube Analysis "){
            steps{
                withSonarQubeEnv('sonar-server') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Terraform \
                    -Dsonar.projectKey=Terraform '''
                }
            }
        }
        stage("quality gate"){
           steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'Sonar-token' 
                }
            } 
        }
        stage('TRIVY FS SCAN') {
            steps {
                sh "trivy fs . > trivyfs.txt"
            }
        }
        stage('Excutable permission to userdata'){
            steps{
                sh 'chmod 777 website.sh'
            }
        }
        stage('Terraform init'){
            steps{
                dir('Jenkins-CICD') {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform plan'){
            steps{
                dir('Jenkins-CICD') {
                    sh 'terraform plan'
                }
            }
        }
        stage('Terraform apply'){
            steps{
                dir('Jenkins-CICD') {
                    sh 'terraform ${action} --auto approve'
                }
            }
        }
    }
}